### ISSUE TITLE
Cosmetic Issue

### ISSUE THREAD

**Issue by heysulo** [kmchmk/SLT-Data-Usage#13]
![image](https://user-images.githubusercontent.com/12120712/129476212-649f8c82-073c-4526-9a8f-df145b123187.png)

For UNLIMITED Plan users, Anytime data is not valid. No value of having there

**Comment by kmchmk** [comment]
> ![image](https://user-images.githubusercontent.com/12120712/129476212-649f8c82-073c-4526-9a8f-df145b123187.png)
> 
> For UNLIMITED Plan users, Anytime data is not valid. No value of having there

Actually it is valid. Unlimited plans have a 1Mbps unlimited connection with a full speed 10GB (or 25GB or 50GB)  limited addon.
One issue here is that "හරය" is "None". I have already [fixed ](https://github.com/kmchmk/SLT-Data-Usage/commit/78d7c48205c432071312133e0a64bdf137bcc350#diff-15153c4ebf25904a215534d36cff47b5ef199421df9cbb0dc686610e0c116fe9)that issue but it is not released yet. I'll release it with the next big release (which is Ubuntu and MacOS support :-) )

Let me know if you prefer the Full Report in any other format.
